global using AutoMapper;
global using Domain.Contracts;
global using Domain.Entities;
global using Shared;
global using Services.Specifications;
global using Shared.Dtos;
global using Microsoft.Extensions.Configuration;
global using Services.Abstraction;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Options;
global using Domain.Exceptions;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Domain.Entities.OrderEntities;
global using Shared.OrderModels;
global using ShippingAddress = Domain.Entities.OrderEntities.Address;
global using Domain.Exceptions.NotFoundExceptions;
global using Microsoft.EntityFrameworkCore;
global using Stripe;
global using Product = Domain.Entities.Product;